### ISSUE TITLE
Bug with DEA Agents card

### ISSUE THREAD

**Issue by a-harris** [rally-the-troops/andean-abyss#2]
Allows all shipments to be removed

![image](https://github.com/rally-the-troops/andean-abyss/assets/41584708/7d193388-a9d8-4595-898b-ea407cc941b3)
![Screenshot_2023-05-12-18-28-09-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/rally-the-troops/andean-abyss/assets/41584708/2d4f916f-7cf8-4f9d-a17f-cccf87ee4309)

**Comment by ccxvii** [comment]
Fixed in commit 6d6a44d.
