### ISSUE TITLE
Abyss game #30476 not recognize active player logued to play

### ISSUE THREAD

**Issue by flv999** [rally-the-troops/andean-abyss#3]
Hello. I have an issue to report in Andean Abyss game #30476.

The interface says "waiting for AUC", and I received the email that I have to play. I am the player who has AUC, but being logged in it does not recognize me to execute the actions. At the game he only lets me in to "observe".

Sorry for the inconvenience.

**Comment by ccxvii** [comment]
Make sure you're logged in and enter the game via the AUC role link.
