### ISSUE TITLE
Oil Spill Card - Event

### ISSUE THREAD

**Issue by fcolmenarez** [rally-the-troops/andean-abyss#5]
It seems the event card allows the Government player to choose cities as well as departments to move to Passive Support. The card is clear that it's just adjacent departments. 

This came up with the sabotaged pipeline between Neiva and Bogota city spaces. The Oil Spill event allowed the Government to pick Neiva to move to Passive Support in addition to Meta West.

**Comment by ccxvii** [comment]
Thanks! I've taken on the fix.

The "events.txt" is the master event file. The event code in rules.js is auto-generated from that file.

**Comment by fcolmenarez** [comment]
Ah ok! Didn't know that. I'll keep it in mind for the future.
